#Requires -Version 5.1
<#
.SYNOPSIS
    Sets up mpv-autoopen: detects mpv/yt-dlp, writes config.ps1, and registers
    the "mpv:" URL protocol for the current user (no admin required).

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\install.ps1

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\install.ps1 -MpvPath "D:\apps\mpv\mpv.exe" -Force
#>
[CmdletBinding()]
param(
    [string]$MpvPath,
    [string]$YtdlpPath,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$vbs        = Join-Path $scriptDir 'mpv-open.vbs'
$ps1        = Join-Path $scriptDir 'mpv-open.ps1'
$configPath = Join-Path $scriptDir 'config.ps1'

Write-Host 'mpv-autoopen installer' -ForegroundColor Cyan
Write-Host ''

foreach ($f in @($vbs, $ps1)) {
    if (-not (Test-Path $f)) { throw "Missing required file: $f" }
}

# --- 1. Locate mpv.exe ------------------------------------------------------
function Find-Mpv([string]$hint) {
    if ($hint -and (Test-Path $hint)) { return (Resolve-Path $hint).Path }
    $cmd = Get-Command 'mpv.exe' -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $candidates = @(
        "$env:ProgramFiles\mpv\mpv.exe",
        "${env:ProgramFiles(x86)}\mpv\mpv.exe",
        "$env:LOCALAPPDATA\Programs\mpv\mpv.exe",
        "$env:USERPROFILE\scoop\apps\mpv\current\mpv.exe",
        "$env:ProgramData\chocolatey\bin\mpv.exe"
    )
    foreach ($c in $candidates) { if ($c -and (Test-Path $c)) { return (Resolve-Path $c).Path } }
    return $null
}

$mpv = Find-Mpv $MpvPath
if (-not $mpv) {
    $mpv = Read-Host 'Could not auto-detect mpv.exe. Enter the full path to mpv.exe'
    $mpv = $mpv.Trim().Trim('"')
}
if (-not $mpv -or -not (Test-Path $mpv)) { throw "mpv.exe not found at: $mpv" }
$mpv = (Resolve-Path $mpv).Path
Write-Host "  mpv.exe : $mpv" -ForegroundColor Green

# --- 2. Locate yt-dlp (prefer the copy next to mpv.exe) --------------------
if (-not $YtdlpPath) {
    $mpvFolder = Split-Path -Parent $mpv
    foreach ($name in @('yt-dlp.exe', 'yt-dlp_x86.exe', 'youtube-dl.exe')) {
        $p = Join-Path $mpvFolder $name
        if (Test-Path $p) { $YtdlpPath = $p; break }
    }
}
if ($YtdlpPath -and (Test-Path $YtdlpPath)) {
    $YtdlpPath = (Resolve-Path $YtdlpPath).Path
    Write-Host "  yt-dlp  : $YtdlpPath" -ForegroundColor Green
} else {
    $YtdlpPath = $null
    Write-Host '  yt-dlp  : (not found next to mpv.exe - mpv will locate it on PATH)' -ForegroundColor Yellow
}

# --- 3. Write config.ps1 ----------------------------------------------------
$ytLine = if ($YtdlpPath) { "'$YtdlpPath'" } else { '$null' }
$configContent = @"
# config.ps1 - generated by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm'). Edit freely.

# Full path to your mpv.exe
`$MpvPath = '$mpv'

# Full path to yt-dlp.exe (`$null lets mpv find it next to mpv.exe / on PATH)
`$YtdlpPath = $ytLine

# Named pipe used to reach a running mpv instance
`$PipeName = 'mpv-autoopen'

# Extra args used ONLY when a NEW mpv instance is started. For a persistent
# "always-on" window that just collects videos, try:
#   `$MpvExtraArgs = @('--idle=yes','--keep-open=yes','--force-window=immediate')
`$MpvExtraArgs = @()
"@

if ((Test-Path $configPath) -and -not $Force) {
    Write-Host "  config.ps1 already exists - keeping it (pass -Force to overwrite)." -ForegroundColor Yellow
} else {
    Set-Content -LiteralPath $configPath -Value $configContent -Encoding UTF8
    Write-Host "  config  : wrote $configPath" -ForegroundColor Green
}

# --- 4. Register the "mpv:" URL protocol (HKCU, no admin) ------------------
$command = "wscript.exe `"$vbs`" `"%1`""
$base    = 'HKCU:\Software\Classes\mpv'

New-Item -Path $base -Force | Out-Null
Set-ItemProperty -Path $base -Name '(default)'    -Value 'URL:mpv Protocol'
Set-ItemProperty -Path $base -Name 'URL Protocol' -Value ''
New-Item -Path "$base\shell\open\command" -Force | Out-Null
Set-ItemProperty -Path "$base\shell\open\command" -Name '(default)' -Value $command
Write-Host "  protocol: mpv: -> $command" -ForegroundColor Green

# --- Done -------------------------------------------------------------------
Write-Host ''
Write-Host 'Setup complete.' -ForegroundColor Cyan
Write-Host ''
Write-Host 'Next steps:'
Write-Host '  1. Load the browser extension:'
Write-Host '       Chrome/Edge -> chrome://extensions -> enable Developer mode'
Write-Host '                   -> Load unpacked -> select the "extension" folder.'
Write-Host '  2. On YouTube, right-click a video thumbnail/link (or the watch page)'
Write-Host '       and choose "Add ... to mpv". The first time, allow the browser'
Write-Host '       to open the mpv: link (tick "Always allow").'
Write-Host ''
Write-Host 'Test it right now without the browser:' -ForegroundColor Cyan
Write-Host "  .\mpv-open.ps1 'https://youtu.be/dQw4w9WgXcQ'"
